# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cloudelivery-mac-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cloudelivery-mac-app
	pod 'lottie-ios'
end
